// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package v1alpha2

// RuleListerExpansion allows custom methods to be added to
// RuleLister.
type RuleListerExpansion interface{}

// RuleNamespaceListerExpansion allows custom methods to be added to
// RuleNamespaceLister.
type RuleNamespaceListerExpansion interface{}
