// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/dpacierpnik/istio-0.7-eds-issue/pkg/clients/config.istio.io/clientset/versioned/typed/config.istio.io/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeConfigV1alpha2 struct {
	*testing.Fake
}

func (c *FakeConfigV1alpha2) Rules(namespace string) v1alpha2.RuleInterface {
	return &FakeRules{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeConfigV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
